server:
  port: 8089
  servlet:
    context-path: /ylab

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ylabft_db
    username: ft_admin
    password: MyP@ss4DB
  sql:
    init:
      schema-locations: fin_tracker

  liquibase:
    change-log: db/changelog/db.changelog-master.yml