package website.ylab.financetracker.service;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PropertiesLoaderUtils;
import org.springframework.stereotype.Service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

/**
 * Provides database connections
 */
@Service
public class ConnectionProviderImplementation implements ConnectionProvider {
    Logger logger = LogManager.getLogger(ConnectionProviderImplementation.class);
    private String url;
    private String user;
    private String password;
    private String schema;
    private String changelog;
    private final String persistenceType = "";

    public ConnectionProviderImplementation() {
        logger.info("DB connection settings: url={}, schema={}, user={}", url, schema, user);
        try {
            Class.forName("org.postgresql.Driver");
            logger.info("DB driver successfully called");
        } catch (ClassNotFoundException e) {
            logger.error("DB driver error");
            throw new RuntimeException(e);
        }
        Resource resource = new ClassPathResource("application.yml");
        try {
            Properties properties = PropertiesLoaderUtils.loadProperties(resource);
            url = properties.getProperty("url");
            user = properties.getProperty("username");
            password = properties.getProperty("password");
            schema = properties.getProperty("schema");
            changelog = properties.getProperty("changelog");
            logger.info("Get DB connection properties: url={}, user={}, password={}, schema={}, changelog={}",
                    url, user, password, schema, changelog);
        } catch (Exception e) {
            logger.error("Can't get database connection properties. {}",  e.getMessage());
            throw new RuntimeException("Can't get database connection properties");
        }
    }

    /**
     * Static method to get connection to Database to run queries
     * @return Connection, generated by DriverManager.getConnection method
     * @throws SQLException as it describe in DriverManager.getConnection method
     */
    @Override
    public Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, password);
    }

    /**
     * Returns schema name from config file
     * @return String schema name
     */
    @Override
    public String getSchema() {
        return schema;
    }

    /**
     * Returns path to master changelog from config file
     * @return String path to master changelog
     */
    @Override
    public String getChangelog() { return changelog; }

    @Override
    public String getPersistenceType() { return persistenceType; }
}